### ISSUE TITLE
Can a :crux.tx/fn fail?

### ISSUE THREAD

**Issue by Vaelatern** [juxt/crux#1077]
Here is my scenario. I want to make a change to a database, checking an invariant before applying the change. I assume I could do this with a `:crux.tx/fn`, but I see no mechanism for a `clojure.core/<` or similar check and then failing if the invariant would be broken with an application of the function.

The documentation I have read is unclear, but perhaps this is already supported and just not documented?

**Comment by caleb** [comment]
I think you can return `false` instead of a vector of operations and it won't alter the db.

**Comment by Vaelatern** [comment]
Will the caller be made aware of the difference?

**Comment by caleb** [comment]
I haven’t tried yet, but I’m assuming you could tel the difference when you call “await-tx”

I’m not at a computer now to try it.
