### ISSUE TITLE
Can valid-time be used in the query?

### ISSUE THREAD

**Issue by qwwwpp** [juxt/crux#1092]
I want to treat the :crux.db/valid-time as last-modified-at, so I try to query the entities whose valid-time is greater than a certain Java.util.time。

But it looks like in the`[?e :crux.db/valid-time ?valid-time]`,  :crux.db/valid-time will be treated as a normal key in the document.
Is there a way to retrieve the crux valid-time in the query?

Here is my code.
```
;;day1 day2:  Java.util.date
(defn day1-is-after-day2
  [day1 day2]
  (-> (.compareTo day1 day2)
      (> 0)))

(crux/q (crux/db node)
               {:find '[?e]
                :where '[[?e :crux.db/valid-time ?valid-time]
                             [(day1-is-after-day2 ?valid-time ?min-last-modified-at)]]
                :args ['?min-last-modified-at min-last-modified-at
                          'day1-is-after-day2 day1-is-after-day2}]
                })

=> #{}
```

**Comment by jonpither** [comment]
Hi @qwwwpp. We don't currently expose valid-time at the query level. This is on our roadmap as we want to extend our temporal functionality - we are currently working our way towards it. I think this issue falls underneath #968, however I'll leave this issue open under we spec #968 out some more.
