### ISSUE TITLE
Can't start-node

### ISSUE THREAD

**Issue by Vaelatern** [juxt/crux#1128]
Installed dependencies:

```
                 [juxt/crux-core "20.09-1.12.0-beta"]
                 [juxt/crux-rocksdb "20.09-1.12.0-beta"]
```

When I try to `start-node`, I get:

```
Execution error at crux.tx/eval31162$loading (tx.clj:1).
No such var: nippy/freeze-to-file
```

On subsequent runs of the same call, I get:

```
Execution error at crux.query/eval31047$loading (query.clj:1).
namespace 'crux.mem-kv' not found
```

If I try to run `(crux/start-node {})` I get the same results.

I feel like I'm missing something obvious.

**Comment by jarohen** [comment]
My first guess here would be a dependency conflict, if `freeze-to-file` has been recently introduced/removed in Nippy. Could you try `lein deps :tree | grep nippy`? We've just bumped to 2.15.1
